package com.healthsim;

import java.awt.Color;
import java.io.*;
import javax.swing.*;
import java.util.*;
import javax.swing.event.CaretEvent;
import javax.swing.text.Highlighter.Highlight;

public class OpenNLPv2 extends javax.swing.JFrame {

    ArrayList<Offset> coordinates;
    File inputFile;
    String selectedTag = "Person";
    String selectedColor = "0000FF";
    String selectedId = "1";
    String[] btns = {
        "Person:0000FF:1",
        "Button 2:BBBBBB:2",
        "Button 3:BBBBBB:3",
        "Button 4:BBBBBB:4",
        "Button 5:BBBBBB:5",
        "Button 6:BBBBBB:6",        
    };
    

    public OpenNLPv2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playground = new javax.swing.JTextPane();
        statusPanel = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        entityLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        load = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        loadButtons = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenNLP Annotator v2");

        playground.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(playground);

        statusPanel.setBackground(new java.awt.Color(248, 248, 248));

        status.setBackground(new java.awt.Color(239, 239, 239));
        status.setText("Status:");
        status.setToolTipText("");

        entityLabel.setForeground(new java.awt.Color(0, 0, 255));
        entityLabel.setText("Person");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(entityLabel))
        );

        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        fileName.setText("No files selected");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Line Breaks");

        btn1.setForeground(new java.awt.Color(0, 0, 255));
        btn1.setText("Person");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Button 2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("Button 3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("Button 4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn6.setText("Button 6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setText("Button 5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addGap(61, 61, 61)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submit)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)))
        );

        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("New");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Open");
        jMenuItem5.setToolTipText("");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Save");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Save As");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Exit");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");

        jMenuItem2.setText("RegExp Settings");
        jMenu2.add(jMenuItem2);

        loadButtons.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        loadButtons.setText("Load Buttons");
        loadButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonsActionPerformed(evt);
            }
        });
        jMenu2.add(loadButtons);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem1.setText("About");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonsActionPerformed
        String userDir = System.getProperty("user.home");
        final JFileChooser fileDialog = new JFileChooser(userDir + "/Desktop");
        int fileStatus = fileDialog.showOpenDialog(this);
        if (fileStatus == JFileChooser.APPROVE_OPTION) {
            inputFile = fileDialog.getSelectedFile();
            String inputdata = Util.readData(inputFile.getPath());
            if (inputdata != null || inputdata != "") {
                String[] buttons = inputdata.split(",");
                for (int i = 0; i < buttons.length - 1; i++) {
                    String button = buttons[i];
                    String name = button.split(":")[0];
                    String color = button.split(":")[1];
                    int id = i + 1;
                    
                    if (i == 0) {
                        entityLabel.setForeground(Color.decode("0x" + color));
                        entityLabel.setText(name);
                        btn1.setForeground(Color.decode("0x" + color));
                        btn1.setText(name);
                        selectedTag = name;
                        selectedColor = color;
                    } else if (i == 1) {
                        btn2.setForeground(Color.decode("0x" + color));
                        btn2.setText(name);
                    } else if (i == 2) {
                        btn3.setForeground(Color.decode("0x" + color));
                        btn3.setText(name);
                    } else if (i == 3) {
                        btn4.setForeground(Color.decode("0x" + color));
                        btn4.setText(name);
                    } else if (i == 4) {
                        btn5.setForeground(Color.decode("0x" + color));
                        btn5.setText(name);
                    } else if (i == 5) {
                        btn6.setForeground(Color.decode("0x" + color));
                        btn6.setText(name);
                    }
                    
                    btns[i] = name + ":" + color + ":" + id;
                }
            } else {
                status.setText("Status: Can't read File");
            }
            status.setText("Status: Buttons loaded");
        }
    }//GEN-LAST:event_loadButtonsActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        selectedTag = btns[0].split(":")[0];
        selectedColor = btns[0].split(":")[1];
        selectedId = btns[0].split(":")[2];
        entityLabel.setText(selectedTag);
        entityLabel.setForeground(Color.decode("0x" + selectedColor));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        selectedTag = btns[1].split(":")[0];
        selectedColor = btns[1].split(":")[1];
        selectedId = btns[1].split(":")[2];
        entityLabel.setText(selectedTag);
        entityLabel.setForeground(Color.decode("0x" + selectedColor));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        selectedTag = btns[2].split(":")[0];
        selectedColor = btns[2].split(":")[1];
        selectedId = btns[2].split(":")[2];
        entityLabel.setText(selectedTag);
        entityLabel.setForeground(Color.decode("0x" + selectedColor));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        selectedTag = btns[3].split(":")[0];
        selectedColor = btns[3].split(":")[1];
        selectedId = btns[3].split(":")[2];
        entityLabel.setText(selectedTag);
        entityLabel.setForeground(Color.decode("0x" + selectedColor));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        selectedTag = btns[4].split(":")[0];
        selectedColor = btns[4].split(":")[1];
        selectedId = btns[4].split(":")[2];
        entityLabel.setText(selectedTag);
        entityLabel.setForeground(Color.decode("0x" + selectedColor));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        selectedTag = btns[5].split(":")[0];
        selectedColor = btns[5].split(":")[1];
        selectedId = btns[5].split(":")[2];
        entityLabel.setText(selectedTag);
        entityLabel.setForeground(Color.decode("0x" + selectedColor));
    }//GEN-LAST:event_btn6ActionPerformed
    
    private void loadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loadActionPerformed
        coordinates.clear(); // clear the values
        String userDir = System.getProperty("user.home");
        final JFileChooser fileDialog = new JFileChooser(userDir + "/Desktop");
        int fileStatus = fileDialog.showOpenDialog(this);
        if (fileStatus == JFileChooser.APPROVE_OPTION) {
            inputFile = fileDialog.getSelectedFile();
            fileName.setText(inputFile.getName());
            String inputdata = Util.readData(inputFile.getPath());
            if (inputdata != null || inputdata != "")
                playground.setText(inputdata);
            else
                status.setText("Status: Can't read File");
            status.setText("Status: File loaded");
        }
    }// GEN-LAST:event_loadActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitActionPerformed
        coordinates = Util.removeSingleChar(coordinates);
        String orgText = playground.getText();
        orgText = orgText.replaceAll("\r", ""); // remove this stupid carriage return

        int prev_index = 0, next_index = orgText.length();
        Collections.sort(coordinates);
        StringBuilder finalData = new StringBuilder();

        for (Offset data : coordinates) {
            int start = data.getStart();
            int end = data.getEnd();
            String id = data.getId();
            String name = "Person";
            
            for (String btn : btns) {
                if (btn.split(":")[2].equals(id)) {
                    name = btn.split(":")[0];
                }
            }
            
            String orgStr = orgText.substring(start, end);
            String newStr = " <START:" + name.trim().toLowerCase() + "> " + orgStr + " <END> ";

            finalData.append(orgText.substring(prev_index, start));
            if (newStr != null)
                finalData.append(newStr);

            prev_index = end;
        }
        finalData.append(orgText.substring(prev_index, next_index));
        String finaldata_with_even_spaces = Util.makeEvenSpaces(finalData.toString());

        if (Util.writeData(finaldata_with_even_spaces,
                inputFile.getParent() + File.separator + "Mod_" + inputFile.getName()) != null) {
            System.out.println("Successfuly Written");
            status.setText("Status: Saved to File");
        } else {
            System.out.println("Error Occured");
            status.setText("Status: Couldn't save File");
        }

    }// GEN-LAST:event_submitActionPerformed

    private void eventListeners() {
        coordinates = new ArrayList<>();

        playground.addCaretListener((CaretEvent e) -> {
            Highlight[] h = playground.getHighlighter().getHighlights();
            for (Highlight h1 : h) {

                int start = h1.getStartOffset();
                int end = h1.getEndOffset();

                Offset offset = new Offset(start, end, selectedId);
                if (coordinates.indexOf(offset) > -1) { // in case people needs to remove annotation
                    if (coordinates.get(coordinates.indexOf(offset)).getId().equals(selectedId)) {
                        coordinates.remove(offset);
                        status.setText("Status: Word Removed");
                    } else {
                        coordinates.remove(offset);
                        status.setText("Status: Word Removed");
                        coordinates = Util.overlapsAdd(offset, coordinates);
                        status.setText("Status: Word added");
                    }
                    // style.setCharacterAttributes(start, (end - start), black, false);
                } else {
                    coordinates = Util.overlapsAdd(offset, coordinates);
                    status.setText("Status: Word added");
                    // style.setCharacterAttributes(start, (end - start), red, true);
                }

                Util.refreshColor(playground);
                Util.colorIt(coordinates, playground, btns);
            }
        });

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenNLPv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenNLPv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenNLPv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenNLPv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        OpenNLPv2 annonator = new OpenNLPv2();
        java.awt.EventQueue.invokeLater(() -> {
            annonator.setVisible(true);
        });

        annonator.eventListeners();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JLabel entityLabel;
    private javax.swing.JLabel fileName;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton load;
    private javax.swing.JMenuItem loadButtons;
    private javax.swing.JTextPane playground;
    private javax.swing.JLabel status;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
